name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jick-dist
        path: .next
    - name: Archive prackage.json
      uses: actions/upload-artifact@v2
      with:
        name: jick-package.json
        path: package.json

  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download dist package
        uses: actions/download-artifact@v2
        with:
          name: jick-dist
          path: jick-dist/
      - name: Download package.json
        uses: actions/download-artifact@v2
        with:
          name: jick-package.json
          path: package.json
      - name: Deploy website
        uses: garygrossgarten/github-action-scp@release
        with:
          local: jick-dist
          privateKey: ${{ secrets.KEY }}
          remote: ${{ secrets.TARGET_DIR }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          rmRemote: true
      - name: Deploy package.json
        uses: garygrossgarten/github-action-scp@release
        with:
          local: package.json
          privateKey: ${{ secrets.KEY }}
          remote: ${{ secrets.PACKAGE_JSON_TARGET_DIR }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          rmRemote: true
