name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jick-dist
        path: .next

  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download dist package
        uses: actions/download-artifact@v2
        with:
          name: jick-dist
      - name: Copy dist to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "jick-dist"
          target: "/var/www/jick/dist"
          rm: True
