name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jick-dist
        path: .next

  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download dist package
        uses: actions/download-artifact@v2
        with:
          name: jick-dist
          path: jick-dist/
      - shell: bash
        env:
          KEY: ${{ secrets.KEY }}
        run: echo $KEY > ./temp_key
      - name: Deploy website
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
        run: scp -rp jick-dist/ -i ./temp_key $USER@$HOST:$TARGET
